export const SECTION_ONE_POST_REQUEST = "SECTION_ONE_POST_REQUEST";
export const SECTION_ONE_POST_SUCCESS = "SECTION_ONE_POST_SUCCESS";
export const SECTION_ONE_POST_FAIL = "SECTION_ONE_POST_FAIL";

export const SECTION_TWO_POST_REQUEST = "SECTION_TWO_POST_REQUEST";
export const SECTION_TWO_POST_SUCCESS = "SECTION_TWO_POST_SUCCESS";
export const SECTION_TWO_POST_FAIL = "SECTION_TWO_POST_FAIL";

export const SECTION_THREE_POST_REQUEST = "SECTION_THREE_POST_REQUEST";
export const SECTION_THREE_POST_SUCCESS = "SECTION_THREE_POST_SUCCESS";
export const SECTION_THREE_POST_FAIL = "SECTION_THREE_POST_FAIL";

export const AUTHOR_REQUEST = "AUTHOR_REQUEST";
export const AUTHOR_SUCCESS = "AUTHOR_SUCCESS";
export const AUTHOR_FAIL = "AUTHOR_FAIL";